###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "email": "tesss2t@example.com",
    "password": "password123",
    "full_name": "Test User",
    "dni": "12341127",
    "role": "admin"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "tesss2t@example.com",
    "password": "password123"
}

###
POST http://localhost:8080/api/patients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzg5MDAzMTAxLCJpYXQiOjE3ODg5OTk1MDF9.ShDh21RHletmpbWgvgg3SIh54tp-MOLEb12gsjXGb9w

{
    "first_name": "John",
    "last_name": "Doe",
    "dni": "12345672",
    "email": "johndoe2@example.com",
    "phone" : "1234567890"
}